---
- name: download package
  get_url: url={{ serverspeeder_url }}
           dest=/tmp/serverSpeederInstaller.tar.gz
  tags:
    - prepare

- name: unarchive
  unarchive: src=/tmp/serverSpeederInstaller.tar.gz
             dest=/tmp/
             mode=755
             copy=no
  tags:
    - prepare

- name: get default interface
  debug: msg={{ ansible_default_ipv4.interface }}
  tags: debug

- name: setup serverspeeder
  shell: ./serverSpeederInstaller.sh -e {{ serverspeeder_user.email }} -p {{ serverspeeder_user.passwd }} -i {{ ansible_default_ipv4.interface }} -r -b -f
  args:
    chdir: /tmp/
  tags: setup
